### ISSUE TITLE
UI Страница Логин

### ISSUE THREAD

**Issue by andreinechaev** [volunteer-prb/podcasts-api#12]
Страница Аутентификации с полями Login/Password 
Использование заглушек на REST запросы к серверу. 
Soft dependency #11 - если задача #11 выполнена, заменить заглушки на реальные запросы
Дизайн - https://www.figma.com/file/wHVcplOhmFMqS1Wv2OgKsP/Conversion-Service?node-id=45%3A2298

**Comment by kuzkovandrey** [comment]
Есть вопрос по поводу ответов бека.
Т.е. фронт шлет при логине и регистрации поля email и password на бэк. Какие поля будут приходить в ответ? Будут ли токены, которые должны рефрешится и как будут называться эти поля?

**Comment by andreinechaev** [comment]
> Есть вопрос по поводу ответов бека. Т.е. фронт шлет при логине и регистрации поля email и password на бэк. Какие поля будут приходить в ответ? Будут ли токены, которые должны рефрешится и как будут называться эти поля?

В данный момент рассматривается сессионная аутентификации, так что в ответ или 200 или 401. В формате 200, `{"message": "Success"}`

**Comment by dkotlyar** [comment]
Прошу учесть, что сейчас `backend` отсылает ответы в [формате](https://github.com/volunteer-prb/podcasts-api/tree/master/webapp/backend#common)
```json
{
  "status": "success",
  "data": {}
}
```
в случае успеха (соответственно статус код `2xx`). Поле `data` содержит информацию (зависит от endpoint), в случае логина там может быть информация о пользователей или session_key

или 
```json
{
  "status": "error",
  "message": "<error_text_for_display>"
}
```
в случае неудачи (статус код `4xx`, `5xx`).
