### ISSUE TITLE
Управление Записями/Records Python

### ISSUE THREAD

**Issue by andreinechaev** [volunteer-prb/podcasts-api#15]
Аутентифицированный пользователь (#11 ) имеет доступ к списку записей Канала. Список формируется автоматически на основе состояния Канала. Пользователь имеет возможность обновить контент - описание, фоновый рисунок и прикрепленную аудиозапись (если таковая присутствует) 
- Реализовать модель Запись (Record)
  - Поля
  - Title
  - Description
  - URL
  - Совместимость с SQLAlchemy
- Создание CRUD операций по управлению записями. Обернуть в систему аутентификации #11 ;
  - Create - На вход принимается ссылка на видео, из которой вытягивается название и другая мета информация (уточнить)
  - Read - две операции, на чтение одного и списка каналов. Возвращает метаинформацию записи
  - Update - Обновляет метаинформацию записи
  - Delete - Удаляет запись из БД

**Comment by dkotlyar** [comment]
Правильно ли я понимаю, что сущность Record это [YoutubeVideo](https://github.com/volunteer-prb/podcasts-api/blob/master/webapp/backend/app/models/video.py) из текущего состояния репозитория?

**Comment by andreinechaev** [comment]
> Правильно ли я понимаю, что сущность Record это [YoutubeVideo](https://github.com/volunteer-prb/podcasts-api/blob/master/webapp/backend/app/models/video.py) из текущего состояния репозитория?

Да, +результат конвертации. Думаю имеет смысл использовать новую таблиц для результатов, тогда имеем зависимость one-to-many  - что дает нам возможность хранить варианты, например после перезагрузки обработанной записи.

**Comment by andreinechaev** [comment]
Completed as part of PR #21
