### ISSUE TITLE
Система уведомлений о новых видео на канале

### ISSUE THREAD

**Issue by andreinechaev** [volunteer-prb/podcasts-api#18]
Реализовать REST точку доступа для уведомлений о новом видео на канале (частично реализована)
Операция создает новую запись record, если таковая не существует. Уведомляет систему (celery #19 ) о новой записи для последующего процессинга

**Comment by dkotlyar** [comment]
Задача реализована в PR #24.

REST точка `/hooks/new/<channel_id>` принимает уведомление о новом видео на канале, создаёт новую запись `YoutubeVideo` и уведомляет систему (media_manager #19) о новой записи, та в свою очередь выполяет свою работу и создаёт новую запись `Record` для `YoutubeVideo`.
